name: Flet APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: pip install flet
    - run: flet build apk
    - uses: actions/upload-artifact@v4
      with:
        name: yst-apk
        path: build/apk/**/*.apk
    - run: |
        echo "✅ APK Built Successfully!"
        echo "⬇️ Download from Artifacts section"
